server:
  port: 8123

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easydemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: czx981103

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml